AAP-5712 Add Ansible on Azure docs
ansible/aap-docs pull request #1
Opened 2022-09-14 10:44 UTC by ariordan-redhat

AAP-5712 Add Ansible on Azure docs to `/titles/aap-on-azure/`

- Add directories for modules, assemblies, titles, common content, images, attributes
- Add symlinks (see `tree` output below)

```
➜  /titles/aap-on-azure/
$ tree .
.
├── aap-common -> ../../aap-common
├── aap-on-azure -> ../../assemblies/aap-on-azure
├── attributes -> ../../attributes
├── images -> ../../images
└── master.adoc

➜  /aap-docs/assemblies/
$ tree .
.
└── aap-on-azure
    ├── aap-on-azure -> ../../modules/aap-on-azure
    ├── assembly-aap-azure-connecting-to-aap.adoc
    ├── assembly-aap-azure-direct-peering.adoc
    ├── assembly-aap-azure-hub-spoke-peering.adoc
    ├── assembly-aap-azure-install.adoc
    ├── assembly-aap-azure-intro.adoc
    ├── assembly-aap-azure-network-peering.adoc
    └── assembly-aap-azure-vwan-peering.adoc
```

2022-09-16 10:29 UTC, oraNod requested changes
One minor thing in this review. I'd like to push a commit and then talk through the changes. Squashing this to a single commit would make it easier to compare.

Also please create an issue and remove all reference to the Jira ticket, including the commit message. Reference the issue number that you create in the new commit message with `#<issue-number>` That way the PR automatically links to the issue.

2022-09-16 10:29 UTC, oraNod commented on .gitignore
> +aap-on-azure.html
```suggestion
*.html
```

2022-09-16 10:36 UTC, ariordan-redhat commented
Created issue 2. Commits squashed.

2022-09-20 09:43 UTC, ariordan-redhat commented
@oraNod Your updates look good to me - thanks.

2022-09-20 12:11 UTC, oraNod approved these changes
LGTM

2022-09-20 12:12 UTC, merged

2022-09-20 12:12 UTC, oraNod commented
Thanks @ariordan-redhat