update backup and restore with 2.4 changes
ansible/aap-docs pull request #173
Opened 2023-07-06 17:47 UTC by prat98

2023-07-06 17:57 UTC, zkayyali812 requested changes

2023-07-06 17:57 UTC, zkayyali812 commented on stories/topics/proc-aws-generate-restore-data-file.adoc
> +  --output-data-file /data/extra_vars.yaml
Keep all examples as .yml for consistency

2023-07-06 17:57 UTC, zkayyali812 commented on stories/topics/proc-aws-generate-restore-data-file.adoc
> +. After running these commands, a `command_generator_data/extra_vars.yaml` template file is created.
same

2023-07-06 17:57 UTC, zkayyali812 commented on stories/topics/proc-aws-run-restore-playbook.adoc
> +$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator aws_restore_stack --data-file /data/extra_vars.yaml
same

2023-07-06 17:57 UTC, zkayyali812 commented on stories/topics/proc-aws-run-restore-playbook.adoc
> +After you have run the playbook successfully, a restored deployment is available in AWS CloudFormation matching the name provided for it in the `extra_vars.yaml` file.
same

2023-07-07 08:07 UTC, ianf77 approved these changes
LGTM

2023-07-07 08:08 UTC, merged