Adding custom inventory script example
ansible/aap-docs pull request #1941
Opened 2024-09-17 09:01 UTC by EMcWhinn

Improved custom inventory script documentation for Controller

https://issues.redhat.com/browse/AAP-11874

Affects `titles/controller-admin-guide`

2024-09-17 13:20 UTC, tvo318 commented on downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
> +The following is an example of a working example of JSON output that {ControllerName} can read in:
```suggestion
The following is a working example of JSON output that {ControllerName} can read for the import:
```

2024-09-17 13:22 UTC, tvo318 commented on downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
> +----
```suggestion
----
For information on how to implement the inventory script, see support article: https://access.redhat.com/solutions/6997130.
```

2024-09-17 13:23 UTC, tvo318 requested changes
Small comments for clarification as requested in the JIRA issue. Thanks for doing this!

2024-09-17 17:39 UTC, AlanCoding commented
Here's examples of inventory files:

https://github.com/ansible/test-playbooks/tree/main/inventories

Here's an example of an inventory script inside of that:

https://github.com/ansible/test-playbooks/blob/main/inventories/changes.py

But a big non-obvious part of this is that it's an executable file, meaning you need to run `chmod +x` for that file and then check it into git. You can see Github indicate this with:

![Screenshot from 2024-09-17 13-31-56](https://github.com/user-attachments/assets/d3509094-9477-4580-987a-63bda05b4295)

The wording here isn't correct, but I want to be clear about what the JSON format means. That's what the inventory script would write to standard out. There is a standard format for this, and it's the same as what `ansible-inventory` outputs.

Inventory scripts don't even necessarily need to be written in python. They can be any executable, and that level of generality is why this is often hard to follow.

2024-11-21 13:07 UTC, EMcWhinn commented
Thanks @tvo318 and @AlanCoding for the extra context here. I've added an "IMPORTANT" admonition and some additional resources. Does this now look okay or is there anything else important missing?

2024-11-22 19:02 UTC, AlanCoding approved these changes

2024-11-25 14:51 UTC, michellemacrh commented
LGTM!

2024-11-25 14:51 UTC, merged