Create removing extension nodes chapter
ansible/aap-docs pull request #219
Opened 2023-07-20 13:23 UTC by ianf77

Added files.

2023-07-20 15:16 UTC, leena-jawale approved these changes

2023-07-21 10:57 UTC, ariordan-redhat requested changes
One typo needs to be foxed. One ingoreable suggestion

2023-07-21 10:57 UTC, ariordan-redhat commented on stories/assembly-gcp-removing-extension-nodes.adoc
> +include::topics/proc_gcp-generate-remove-data-files.adoc[leveloffset=+1]
```suggestion
include::topics/proc-gcp-generate-remove-data-files.adoc[leveloffset=+1]
```

2023-07-21 10:57 UTC, ariordan-redhat commented on stories/topics/proc-gcp-update-remove-data-file.adoc
> +[id="proc-gcp-update-remove-data-file"]
Would it make sense to change the ID and filename, so that the URL for the published doc agrees with them?

2023-07-21 12:39 UTC, ariordan-redhat approved these changes
LGTM

2023-07-21 12:39 UTC, merged