Further changes to AAP on GCP doc
ansible/aap-docs pull request #28
Opened 2022-11-18 15:45 UTC by ianf77

A lot of changes

2022-11-21 17:08 UTC, ariordan-redhat commented on stories/assembly-aap-gcp-automation-workloads.adoc
> +Consult your GCP offer used when deploying {AAPonGCP}.
```suggestion
Refer to your GCP offer used when deploying {AAPonGCP}. 
```

2022-11-21 17:11 UTC, ariordan-redhat commented on stories/assembly-aap-gcp-intro.adoc
> +{AutomationMeshStart} is not available on {AAPonGCP} at this time and is planned for a later release.
```suggestion
{AutomationMeshStart} is not available on {AAPonGCP} at this time.
```
Suggestion: don't mention the future plans, or customers will plague support, asking when it'll be included.

2022-11-21 17:44 UTC, ariordan-redhat requested changes
There's a typo, but the rest of the comments are just suggestions.

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/con-aap-gcp-required-apis.adoc
> +On marketplace deployment, the process automatically attempts to enable the followwing APIs.
```suggestion
On marketplace deployment, the process automatically attempts to enable the following APIs. 
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-application-deploy.adoc
> +Now that you have launched the public or private offer, you can begin configuration before deploying the application.
Do we need to say "public or private" ?

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-application-deploy.adoc
> +The zone must be in the *Region* you selected before.
```suggestion
The zone must be in the *Region* you selected.
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-application-deploy.adoc
> +This warning is expected and not a cause for concern.
```suggestion
This warning is expected and is not a cause for concern. 
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-secure-communication-SSL.adoc
> +We will modify the internal load balancers, which have the suffix int-lb
```suggestion
To modify the internal load balancers, which have the suffix int-lb
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-secure-communication-SSL.adoc
> +. Click btn:[Frontend configuration]
```suggestion
. Click btn:[Frontend configuration].
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-secure-communication-SSL.adoc
> +.. If you have not added your certificate, click btn:[CREATE A NEW CERTIFICATE]
```suggestion
.. If you have not added your certificate, click btn:[CREATE A NEW CERTIFICATE].
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-secure-communication-SSL.adoc
> +.. Provide a name for your certificate
```suggestion
.. Provide a name for your certificate.
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-secure-communication-SSL.adoc
> +. Click btn:[Done]
```suggestion
. Click btn:[Done].
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-secure-communication-SSL.adoc
> +. Click btn:[Update], and confirm update
```suggestion
. Click btn:[Update], and confirm update.
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/proc-aap-gcp-secure-communication-SSL.adoc
> +. Click btn:[Edit]
```suggestion
. Click btn:[Edit].
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-automation-performance.adoc
> +{AAPonGCP} is driven using three m5.large instances, two of which run {PlatformName} {ControllerName} and one which runs {HubName}. The {ControllerName} instances collectively support a standard work
Do we need to format `m5.large` ?

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-automation-performance.adoc
> +Testing this operating criteria by Red Hat found support for up-to 10 forks each.
Is the dash in "up-to" necessary?

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-automation-performance.adoc
> +This operating criteria above has been set and tested using output-intensive, “chatty” workloads that produce 2 messages 7 seconds apart on both {ControllerName} nodes.
```suggestion
This operating criteria has been set and tested using output-intensive, “chatty” workloads that produce 2 messages 7 seconds apart on both {ControllerName} nodes. 
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-automation-performance.adoc
> +Testing this operating criteria by Red Hat found support for up-to 10 forks each.
```suggestion
Red Hat has tested the operating criteria for up-to 10 forks each.  
```
Suggesting that this be re-phrased.  My attempt could be misinterpreting the sentence, though.

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-external-load-balancer.adoc
> +This is not recommended as a best practice for security reasons, however this implementation can be secured with different GCP tools.  This section describes how to connect a load balancer that faces
```suggestion
This is not recommended as a best practice for security reasons.
However, this implementation can be secured with different GCP tools.  
This section describes how to connect a load balancer that faces the public internet, but it does not include steps to harden access through Google’s security products. 
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-external-load-balancer.adoc
> +.A load balancer has now been created.
```suggestion
A load balancer has now been created. 
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-external-load-balancer.adoc
> +.Configure the DNS record for the domain that you used in your SSL certificate to point to the IP address of the load balancer.
```suggestion
. Configure the DNS record for the domain that you used in your SSL certificate to point to the IP address of the load balancer.  
```
Is this a separate step?

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-external-load-balancer.adoc
>  You can log after you retrieve the admin password.
```suggestion
You can log in after you retrieve the admin password.
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-networking-options.adoc
> +Must be a minimum “/24” segment and must be in the private network range (192.168 or 10.0).
```suggestion
Must be a minimum “/24” segment and must be in the private network range (192.168 or 10.0).  CIDR ranges be enclosed in backticks? `/24`
```

2022-11-21 17:44 UTC, ariordan-redhat commented on stories/topics/ref-aap-gcp-security-considerations.adoc
> +Securing infrastructure services is an important step to any cloud deployment.
```suggestion
Securing infrastructure services is an important step in any cloud deployment. 
```

2022-11-22 10:38 UTC, ianf77 commented on stories/topics/ref-aap-gcp-automation-performance.adoc
> +{AAPonGCP} is driven using three m5.large instances, two of which run {PlatformName} {ControllerName} and one which runs {HubName}. The {ControllerName} instances collectively support a standard work
I've not seen it formatted before.

2022-11-22 11:24 UTC, ariordan-redhat approved these changes
Looks good to me

2022-11-22 11:41 UTC, ariordan-redhat approved these changes

2022-11-22 11:42 UTC, merged