Add AWS Extension Node Documentation
ansible/aap-docs pull request #29
Opened 2022-11-22 17:24 UTC by zkayyali812

PR to add documentation about how to add extension nodes to AAP on AWS

2022-11-23 15:31 UTC, prat98 commented on stories/topics/ref-aap-aws-add-extension-nodes.adoc
> +.. Replace the *New launch template name* with the name 'extension-group-template' and ensure the checkbox for *Create an Auto Scaling group using the new template* is checked. Click Copy.
Making this bold would make it easier to find
```suggestion
.. Replace the *New launch template name* with the name *extension-group-template* and ensure the checkbox for *Create an Auto Scaling group using the new template* is checked. Click Copy.
```

2022-11-24 18:37 UTC, ariordan-redhat commented
@zkayyali812 
I created a PR to your branch for changes to the procedure module.

2022-11-24 18:39 UTC, ariordan-redhat requested changes
Need to include the assembly in stories.adoc
Suggested changes to the topic file in a PR to your branch.

2022-11-28 12:56 UTC, zkayyali812 commented on stories/assembly-aap-aws-extension-nodes.adoc
> +ifdef::context[:parent-context: {context}]
Great catch! I just added this to the stories.adoc in the most recent commit

2022-11-28 16:54 UTC, ariordan-redhat commented on stories/topics/ref-aap-aws-add-extension-nodes.adoc
> +. Under *Launch Template*, click btn[Create a launch template version] to create a new version of the launch template.
```suggestion
. Under *Launch Template*, click btn:[Create a launch template version] to create a new version of the launch template.
```

2022-11-28 17:03 UTC, ariordan-redhat requested changes
Fix asciidoc formatting for UI elements

2022-11-28 17:09 UTC, ariordan-redhat approved these changes
LGTM

2022-11-28 17:09 UTC, merged