Changes to AWS Removing Extension nodes chapter
ansible/aap-docs pull request #86
Opened 2023-04-21 12:16 UTC by ianf77

Preliminary PR

2023-05-01 13:10 UTC, zkayyali812 approved these changes

2023-05-04 09:37 UTC, ariordan-redhat requested changes
Added suggestions to update included files - I guessed the filenames, though, so best. to check my suggestions first.

2023-05-04 09:37 UTC, ariordan-redhat commented on stories/assembly-aap-aws-removing-extension-nodes.adoc
> +include::topics/proc-aap-aws-generate-data-files.adoc[leveloffset=+1]
```suggestion
include::topics/proc-aap-aws-generate-remove-data-files.adoc[leveloffset=+1]
```

2023-05-04 09:37 UTC, ariordan-redhat commented on stories/assembly-aap-aws-removing-extension-nodes.adoc
> +include::topics/proc-aap-aws-update-data-file.adoc[leveloffset=+1]
```suggestion
include::topics/proc-aap-aws-update-remove-data-file.adoc[leveloffset=+1]
```

2023-05-04 09:53 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-generate-remove-data-files.adoc
> +This template file resembles the following:-
```suggestion
This template file resembles the following:
```

2023-05-04 09:55 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-removing-extension-nodes.adoc
> +Provides the following command:
```suggestion
The command generator output provides the following command:
```

2023-05-04 09:56 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-update-remove-data-file.adoc
> +The values below are provided as examples:
```suggestion
The values below are provided as examples.
```

2023-05-04 09:57 UTC, ariordan-redhat reviewed
Just a few suggestions.

2023-05-04 11:55 UTC, merged