AWS Install Updates
ansible/aap-docs pull request #88
Opened 2023-04-25 07:35 UTC by ianf77

Updated, largely putting iam policies into a table

2023-04-25 07:36 UTC, ianf77 commented
I've put the iams policies into a table, it's more convenient than a list two pages long.

2023-05-05 16:12 UTC, zkayyali812 approved these changes

2023-05-09 08:58 UTC, ariordan-redhat requested changes
Asciidoc artefact and a few other minor comments

2023-05-09 08:58 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-deploy-existing-vpc.adoc
> +This following procedure uses an existing VPC network to deploy an application.
```suggestion
The following procedure uses an existing VPC network to deploy an application.
```

2023-05-09 08:58 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-deploy-existing-vpc.adoc
> +. For Step 3, *Configure stack options* no changes are necessary.
```suggestion
. For Step 3, *Configure stack options*, no changes are necessary. 
```

2023-05-09 08:58 UTC, ariordan-redhat commented on stories/topics/ref-aap-aws-iam-policies.adoc
> +The following table contains a list of necessary IAM policies
```suggestion
The following table contains a list of necessary IAM policies:
```

2023-05-09 09:18 UTC, ariordan-redhat approved these changes
LGTM

2023-05-09 09:19 UTC, merged