Update the AWS Upgrade information
ansible/aap-docs pull request #91
Opened 2023-04-28 10:03 UTC by ianf77

Two stages of procedures added so far

2023-05-04 14:59 UTC, zkayyali812 requested changes
2 minor comments

2023-05-04 14:59 UTC, zkayyali812 commented on stories/topics/proc-aap-aws-upgrade-pull-container-image.adoc
> +====
We should also add the AMEA region image pulling instruction too.

2023-05-05 12:32 UTC, zkayyali812 approved these changes

2023-05-05 12:32 UTC, zkayyali812 commented on stories/topics/proc-aap-aws-backup-platform-stack.adoc
> +. Pull the `ansible-on-clouds-ops 2.3` container image tag must match with theversion you want to upgrade to.
```suggestion
. Pull the `ansible-on-clouds-ops 2.2` container image tag must match with theversion you want to upgrade to.
```

2023-05-09 08:38 UTC, ariordan-redhat reviewed
Review not fully completed

2023-05-10 10:23 UTC, ariordan-redhat requested changes
Essential changes: concept -> context

The rest are just suggestions.

2023-05-10 10:23 UTC, ariordan-redhat commented on stories/topics/ref-aws-update-upgrade-data-file.adoc
> +* `aws_region`` is the region where the foundation deployment is located.
```suggestion
* `aws_region` is the region where the foundation deployment is located.
```

2023-05-10 10:23 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-upgrade-pull-container-image.adoc
> ++
```suggestion

```

The `+` shows up in the built doc.

2023-05-10 10:23 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-upgrade-pull-container-image.adoc
> +for EMEA regions (Europe, Middle East, Africa) run the following command instead:
```suggestion
For EMEA regions (Europe, Middle East, Africa) run the following command instead:
```

2023-05-10 10:23 UTC, ariordan-redhat commented on stories/topics/proc-aws-from-stack-prepare-environment.adoc
> +The keypair used must exist in the aws region you are restoring to.
```suggestion
The keypair used must exist in the AWS region you are restoring to.
```

2023-05-10 10:23 UTC, ariordan-redhat commented on stories/topics/proc-aws-generate-upgrade-data-file.adoc
> +. Create a folder to hold the configuration files
```suggestion
. Create a folder to hold the configuration files.
```

2023-05-10 10:23 UTC, ariordan-redhat commented on stories/topics/proc-aws-generate-upgrade-data-file.adoc
> +. Populate the `command_generator_data` folder with configuration file template.
```suggestion
. Populate the `command_generator_data` folder with the configuration file template.
```

2023-05-10 10:23 UTC, ariordan-redhat commented on stories/topics/proc-aws-from-stack-pull-container-image.adoc
> +for EMEA regions (Europe, Middle East, Africa) run the following command instead:
```suggestion
For EMEA regions (Europe, Middle East, Africa) run the following command instead:
```

2023-05-10 10:23 UTC, ariordan-redhat requested changes
Essential changes: concept -> context

The rest are just suggestions.

2023-05-10 10:25 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-upgrade-pull-container-image.adoc
> +
```suggestion
+
```

2023-05-10 10:27 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-upgrade-pull-container-image.adoc
> +. Pull the Docker image for Ansible on Clouds operational container with the same tag as the version you want to upgrade to.
Bullet point instead of number for a one-step procedure?

2023-05-10 10:53 UTC, merged