Updated AWS add extension nodes
ansible/aap-docs pull request #93
Opened 2023-05-01 10:41 UTC by ianf77

Added files (see PR for notes)

2023-05-01 13:10 UTC, zkayyali812 approved these changes

2023-05-02 08:45 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-deploying-extension-nodes.adoc
> +Provides the following command:
```suggestion
Provides the following upgrade command:
```
Just a suggestion: the next step in the procedure refers to this as the upgrade command

2023-05-02 09:20 UTC, ariordan-redhat requested changes

2023-05-02 09:20 UTC, ariordan-redhat commented on stories/assembly-aap-aws-deploying-extension-nodes.adoc
> +include::topics/proc-aa-aws-update-add_data-files.adoc[leveloffset=+1]
```suggestion
include::topics/proc-aa-aws-update-add-data-files.adoc[leveloffset=+1]
```

2023-05-02 09:20 UTC, ariordan-redhat commented on stories/assembly-aap-aws-deploying-extension-nodes.adoc
> +include::topics/proc-aap-aws-deploying_extension-nodes.adoc[leveloffset=+1]
```suggestion
include::topics/proc-aap-aws-deploying-extension-nodes.adoc[leveloffset=+1]
```

2023-05-04 15:08 UTC, zkayyali812 commented on stories/topics/proc-aap-aws-deploying-extension-nodes.adoc
> +aws_backup_iam_role_arn=arn:aws:iam::<YOUR_ACCOUNT_NUMBER>:role/service-role/AWSBackupDefaultServiceRole'
```suggestion
docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials \
--env ANSIBLE_CONFIG=../aws-ansible.cfg  $IMAGE redhat.ansible_on_clouds.aws_add_extension_nodes \
-e 'aws_foundation_stack_name=AnsibleAutomationPlatform aws_region=us-east-1 \ aws_launch_template_name=AnsibleAutomationPlatform-ext-lt1-100 \ 
aws_autoscaling_group_name=AnsibleAutomationPlatform-ext-asg1-100 \
aws_asg_min_size=2 aws_asg_desired_capacity=2 aws_offer_type=100'
```

2023-05-04 15:10 UTC, zkayyali812 requested changes
Not an upgrade procedure, remove word upgrade where used

2023-05-04 15:10 UTC, zkayyali812 commented on stories/topics/proc-aap-aws-deploying-extension-nodes.adoc
> +Provides the following upgrade command:
Please remove the word `upgrade` from this line

2023-05-10 13:14 UTC, ariordan-redhat reviewed
A few suggestions

2023-05-10 13:14 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-generate-add-data-files.adoc
> +This template file resembles the following:-
```suggestion
This template file resembles the following:
```

2023-05-10 13:14 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-update-add-data-files.adoc
> +* `aws_asg_desired_capacity` is the AutoScalin Group desired capacity.
```suggestion
* `aws_asg_desired_capacity` is the AutoScaling Group desired capacity.
```

2023-05-10 13:14 UTC, ariordan-redhat commented on stories/topics/proc-aap-aws-update-add-data-files.adoc
> +The values are provided as examples:
```suggestion
The values are provided as examples.
```

2023-05-10 13:14 UTC, ariordan-redhat commented on stories/topics/con-aap-aws-pull-deploy-container-image.adoc
Can we delete this file and remove the `include` from `assembly-aap-aws-deploying-extension-nodes.adoc`, or are you planning to add content to the module later ?

2023-05-10 13:14 UTC, ariordan-redhat reviewed
A few suggestions

2023-05-10 14:37 UTC, ianf77 commented on stories/topics/con-aap-aws-pull-deploy-container-image.adoc
Sorry. I added the content.

2023-05-10 15:04 UTC, merged